# Generated by Django 4.2.14 on 2024-07-18 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_utc",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 7, 16, 13, 45, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("temperature", models.FloatField(default=0)),
                ("solar_radiation", models.FloatField(default=0)),
                ("wind_speed", models.FloatField(default=0)),
                ("wind_direction", models.FloatField(default=0)),
                ("relative_humidity", models.FloatField(default=0)),
                ("location", models.TextField(default="Sample")),
            ],
        ),
    ]
