# Generated by Django 4.2.14 on 2024-07-18 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadexcel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="exceldata", name="id",),
        migrations.AlterField(
            model_name="exceldata",
            name="timestamp_utc",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 16, 13, 45, tzinfo=datetime.timezone.utc
                ),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
