# Generated by Django 4.2.14 on 2024-07-18 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DateTime",
            fields=[
                (
                    "datetime",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 7, 16, 13, 45, tzinfo=datetime.timezone.utc
                        ),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "location",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("temperature", models.FloatField()),
                ("solar_radiation", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("wind_direction", models.FloatField()),
                ("relative_humidity", models.FloatField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_data.location",
                    ),
                ),
                (
                    "timestamp_utc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_data.datetime",
                    ),
                ),
            ],
        ),
    ]
